### ISSUE TITLE
Website is very outdated.

### ISSUE THREAD

**Issue by trusktr** [webcomponents/custom-elements-everywhere#1070]
Can someone please have a look? And/or add new maintainers to help out with this?

Solid for example shows 0% on the website (https://custom-elements-everywhere.com/#solid) and the PR has been open for quite a while: https://github.com/webcomponents/custom-elements-everywhere/pull/1005.

Another option could be one of us can fork it and put it up on a new domain.

**Comment by ryansolid** [comment]
The PR got merged and the site still hasn't updated. It appears that something has broken the build process along the way in terms of updating the site automatically.

**Comment by kherge** [comment]
Looks like the site builder uses the now defunct Travis CI. It needs to be updated to use something else, like GitHub Actions.

**Comment by robdodson** [comment]
Hey folks, sorry for the delay on this. I recently left Google and have been taking a break from coding for a while. Just trying to recharge a bit 🔋

If anyone would be interested in taking over the project I'd be happy to transfer the repo and domain to them.

**Comment by rictic** [comment]
Thanks to @robdodson for holding my hand and answering a bunch of questions. I've updated the CI infrastructure, gone through the PR backlog, and updated most (all?) libraries to their latest versions
