### ISSUE TITLE
Add svelte

### ISSUE THREAD

**Issue by robdodson** [webcomponents/custom-elements-everywhere#12]
Svelte 1.37 now supports Custom Elements!
https://github.com/sveltejs/svelte/issues/797

**Comment by mattdsteele** [comment]
Would love to see Svelte on here, but I believe 1.37's feature is that now _exports_ custom elements, a la Stencil's.

I'm not 100% on how Svelte interops with other CEs; the guide isn't entirely clear if it handles bindings via props or attrs.

**Comment by robdodson** [comment]
I think we could write some simple components to test their implementation.
I'd want to make sure that they're creating shadow roots, and that I can
pass in data as attrs or props

**Comment by sisou** [comment]
Svelte 2.5.1 is currently represented on the site. Does this close this issue?

**Comment by robdodson** [comment]
Yep!
