### ISSUE TITLE
Vue 3.x does not support mixed cased custom events

### ISSUE THREAD

**Issue by coryrylan** [webcomponents/custom-elements-everywhere#1204]
In Vue 2, mixed-cased custom events worked with its template binding syntax. However, in Vue 3, this is no longer the case, making it impossible to bind to any custom event that is not all lowercase.

Related Issues:
https://github.com/vuejs/vue-next/issues/2460 
https://github.com/vmware/clarity/issues/6342

Example:
https://stackblitz.com/edit/node-b6p3m4

**Comment by rictic** [comment]
Further related: #1388 and https://github.com/vuejs/core/issues/5401

**Comment by rictic** [comment]
This is fixed in the sense that I've updated the tests to Vue 3 and its score now reflects this limitation
