### ISSUE TITLE
Add stenciljs

### ISSUE THREAD

**Issue by robdodson** [webcomponents/custom-elements-everywhere#13]
Similar to #12, stenciljs outputs custom elements now so let's see if they comply with the tests. We'd be looking to check how they handle attributes and properties, events, etc. We know stencil doesn't use shadow dom so there would be a few test failures there I think, but good to identify and track all of this stuff, especially as stencil evolves.

**Comment by robdodson** [comment]
It might be interesting to test both. We could maybe have two sections on the site, Stencil w/ Shadow DOM and Stencil without. If you're interested in putting together a PR with some tests that would be awesome 😁

cc @adamdbradley as an fyi.

**Comment by arjunyel** [comment]
Hi I have a first stab at Stencil but I need help to finish @robdodson @dahfazz @jthoms1

https://github.com/arjunyel/custom-elements-everywhere/tree/stencil-second-try

First of all I fail all the tests with some variation of `HeadlessChrome 72.0.3626 (Mac OS X 10.14.2) advanced support events can declaratively listen to a PascalCase DOM event dispatched by a Custom Element FAILED
        TypeError: Cannot read property 'querySelector' of null
            at Context.<anonymous> (tests.webpack.js:621:2603)`

So Im not sure if my components are even getting loaded properly? The problem for me is its not throwing an error anywhere saying I did something wrong.

Also I get this message about the tests failing, I know nothing about Karma but I can't see anything wrong consider I just copied my tests from Polymer `[karma-server]: Error: Missing weight! Test: "before each" hook for "will pass boolean data as either an attribute or a property"
    at tests.forEach.test (/Users/rush/go/src/github.com/arjunyel/custom-elements-everywhere/libraries/__shared__/karma-plugins/karma-custom-json-reporter/index.js:156:13)`

Thank you for any help in advance!

**Comment by robdodson** [comment]
hey @arjunyel, can you start a pull request and we can work through it in there?

**Comment by arthurhamon** [comment]
+1

**Comment by arjunyel** [comment]
Now that stencil 1 is out I'll start work on this again

**Comment by arjunyel** [comment]
PR: https://github.com/webcomponents/custom-elements-everywhere/pull/618

**Comment by rictic** [comment]
Looks like this was fixed in #618 and is deployed at https://custom-elements-everywhere.com/#stencil
