### ISSUE TITLE
Which version of hyperHTML should we report?

### ISSUE THREAD

**Issue by robdodson** [webcomponents/custom-elements-everywhere#177]
@WebReflection The site displays the library version under test:

![image](https://user-images.githubusercontent.com/1066253/33737251-4c0d8bd4-db4a-11e7-8150-6622db244c75.png)

However, with hyperhtml we're actually entirely using hyperhtml-element now, instead of hyperhtml itself. Would you rather show the hyperhtml version or the hyperhtml-element version?

**Comment by WebReflection** [comment]
Tests are using both HyperHTMLElement class and plain hyperHTML.

The fact HyperHTMLElement now ships with hyperHTML included is mostly webpack fault incapable of requiring properly ESM 😂

**Comment by WebReflection** [comment]
Btw, if you prefer showing HyperHTMLElement instead I’m fine with that. Your pick

**Comment by robdodson** [comment]
> Tests are using both HyperHTMLElement class and plain hyperHTML.

oh yeah I guess that's true. I think what I ultimately want to point at is whatever version of hyperhtml is shipping with the version of hyperhtml-element that we use
