### ISSUE TITLE
Update babel-preset-es2015 to babel-preset-env

### ISSUE THREAD

**Issue by antgonzales** [webcomponents/custom-elements-everywhere#224]
Several libraries are outputting the following during `npm install`:

>npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!

Each project should be updated to remove this recommendation warning.

**Comment by rictic** [comment]
I believe this is now fixed
