### ISSUE TITLE
appreciate your feedback for custom element reactions diagram

### ISSUE THREAD

**Issue by AndyOGo** [webcomponents/custom-elements-everywhere#438]
I just released an adapted version of the interactive react lifecycle methods diagram for custom element reactions:
https://andyogo.github.io/custom-element-reactions-diagram/

If you have time, I would appreciate your feedback very much.

**Comment by robdodson** [comment]
That's a really cool diagram. @justinfagnani do you know if something like this might be useful for LitElement docs?

**Comment by robdodson** [comment]
btw if it's ok I'm going to close this issue so it doesn't look like a bug. But happy to continue discussion here.

**Comment by AndyOGo** [comment]
Great, glad you like.

Actually I would realy like to inspire any custom element library that they visualize their custom lifecycle hooks in a similiar or even better maner or build on top of it😃
