### ISSUE TITLE
Travis CI: No 'GITHUB_TOKEN' environment variable defined

### ISSUE THREAD

**Issue by DimitarD** [webcomponents/custom-elements-everywhere#473]
I have created a pull request in order to add the smart-elements framework to this repository: #462. Locally, the basic test passes, but Travis CI fails with a message regarding GITHUB_TOKEN: https://travis-ci.org/webcomponents/custom-elements-everywhere/builds/510811429?utm_source=github_status&utm_medium=notification.

Could someone, please, clarify how this issue can be addressed?

**Comment by robdodson** [comment]
Hey @DimitarD this should be fixed now. But please take a look at the discussion over in https://github.com/webcomponents/custom-elements-everywhere/pull/451 about adding new frameworks.
