### ISSUE TITLE
Sort frameworks by score instead of alphabetical order

### ISSUE THREAD

**Issue by astorije** [webcomponents/custom-elements-everywhere#68]
I think it would be fair and rewarding to see frameworks ordered by their overall score rather than their name. What do you think?

**Comment by robdodson** [comment]
I think I prefer alphabetical order because I don't want it to come across as shaming anyone or putting excess pressure on them. I know all the framework authors have a ton on their plate, just want to make sure web components stay on their radar :)

**Comment by astorije** [comment]
Fair enough, thanks for the justification! :)
