### ISSUE TITLE
JSDom

### ISSUE THREAD

**Issue by bennypowers** [webcomponents/custom-elements-everywhere#700]
I'd love to see JSDom's support on the page.

**Comment by trusktr** [comment]
I don't think that would make sense. JSDom is not a frame work on top of DOM, rather it emulates DOM itself. custom-elements-everywhere is documenting whether framework play with with DOM.

**Comment by rictic** [comment]
Yeah, currently the tests are focused on systems that produce and manipulate HTML in a browser. Having good CE support in JSDom is a priority, but I don't think it's a good match for the tests that CE-everywhere runs
