### ISSUE TITLE
Link to CE best practices on /web

### ISSUE THREAD

**Issue by robdodson** [webcomponents/custom-elements-everywhere#8]
It'd be good to link to the [primer](https://developers.google.com/web/fundamentals/architecture/building-components/customelements) and the [best practices](https://developers.google.com/web/fundamentals/architecture/building-components/best-practices) docs.

**Comment by FluorescentHallucinogen** [comment]
@robdodson See also https://github.com/webcomponents/gold-standard/wiki, https://github.com/afonsopacifer/web-components-good-practices, https://github.com/mateusortiz/webcomponents-the-right-way, and partially https://github.com/obetomuniz/awesome-webcomponents. :wink:
