### ISSUE TITLE
Accessibility: Repetitive heading structure for screen readers

### ISSUE THREAD

**Issue by Paul-Hebert** [webcomponents/custom-elements-everywhere#801]
Hey, thanks for the awesome site! This has been _super_ useful for some web components research I've been doing!

I noticed one issue that could potentially make the site difficult to navigate for screen reader users (or search engine crawlers).

Screen reader users can navigate the page by jumping to headings (`h1`, `h2`, `h3`, etc.) For example, in VoiceOver you can use the "rotor" feature to get a list of all headings on the page and then jump to a specific heading based on it's text. This can be a very quick way to navigate the page.

For example imagine a screen reader user was interested in compatibility between React and web components. They hit the home page, open the rotor, and search for a heading containing the text "React." This is the heading structure they see instead:

```
H1 — Custom Elements Everywhere 
H2 — Making sure frameworks and custom elements can be BFFs 🍻 
H2 — What's this? 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H4 — Handling data 
H4 — Handling events 
H3 — Related Issues 
H4 — Yay! No open issues! 
H2 — Frequently Asked Questions 
H3 — What are these custom element things? 
H3 — Are you testing that libraries let you author custom elements? 
H3 — Why is each test counted twice? 
H3 — How are the libraries scored? 
H3 — How are basic and advanced tests different? 
H3 — I thought the whole point of Polymer was to write custom elements. Why doesn't it get a 100%? 
H3 — If a library is missing a feature, like declarative event or property bindings, does it automatically fail those tests? 
H3 — Why don't you have tests for _____ library? 
H3 — I want to write some tests for _____ library. Do you accept pull requests? 
```

This was output by running this snippet on the home page: 

```
[...document.querySelectorAll('h1, h2, h3, h4, h5, h6')].forEach(heading => {
  console.log(`${heading.tagName} — ${heading.innerText}`)
});
```

As you can see, it would be difficult to find information about React using the rotor heading navigation strategy. Instead they'd need to search the page for a string containing "react" or read through the full document.

Similarly search engines use headings to determine and catalogue page content. If the headings do not describe the content well it can be difficult for search engines to understand the content.

I think each framework section should likely have a heading structure like this instead:

```
H3 — React
H4 — Handling data 
H4 — Handling events 
H4 — Related Issues 
```

Ideally this change would be made without any visual changes by using CSS to maintain the current styles and layout.

Let me know what you think. I could spend some time putting together a PR if this is something you're interested in.

Thanks!

**Comment by robdodson** [comment]
good catch, yeah i agree we should make this change!

**Comment by Paul-Hebert** [comment]
Awesome! I'll try to get to that today or tomorrow
